name: Build on Pull Request Merge

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите вашу версию Node.js

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run the Vite build, excluding `assets`
      - name: Build project
        run: |
          export IGNORE_ASSETS="./assets"
          echo "Ignoring $IGNORE_ASSETS"
          if [ -d $IGNORE_ASSETS ]; then mv $IGNORE_ASSETS /tmp/assets; fi
          npm run build
          if [ -d /tmp/assets ]; then mv /tmp/assets ./assets; fi
